<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<AzureFunctionsVersion>V4</AzureFunctionsVersion>
		<OutputType>Exe</OutputType>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<!-- https://github.com/Azure/azure-functions-host/issues/5756#issuecomment-599751436 -->
		<_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput>
		<ExcludeGeneratedDebugSymbol>false</ExcludeGeneratedDebugSymbol>
	</PropertyGroup>

	<ItemGroup>
		<FrameworkReference Include="Microsoft.AspNetCore.App" />
		<PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.Cosmos" Version="9.5.1" />
		<PackageReference Include="FluentEmail.Smtp" Version="3.0.2" />
		<PackageReference Include="Microsoft.ApplicationInsights.WorkerService" Version="2.23.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="2.50.0-preview1" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.ApplicationInsights" Version="2.0.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http.AspNetCore" Version="2.0.2" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.ServiceBus" Version="5.24.0" />
		<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="2.0.5" />
		<PackageReference Include="TextPress" Version="1.0.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Nodsoft.Mercury.Data\Nodsoft.Mercury.Data.csproj" />
	  <ProjectReference Include="..\Nodsoft.Mercury.Models\Nodsoft.Mercury.Models.csproj" />
	  <ProjectReference Include="..\Nodsoft.Mercury.ServiceDefaults\Nodsoft.Mercury.ServiceDefaults.csproj" />
	</ItemGroup>

</Project>
