<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
	  <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.Cosmos" />
	  <PackageReference Include="JetBrains.Annotations" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Cosmos" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

</Project>
